# Generated by Django 2.1.5 on 2019-02-04 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0002_auto_20180322_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedtoken',
            name='oidc_profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.KEYCLOAK_OIDC_PROFILE_MODEL
            ),
        ),
    ]
